name: passkit
description: Plugin for work with PassKit Framework (Apple Pay and Wallet)
version: 1.0.0
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  dio: ^3.0.8
  path_provider: ^1.6.0
  uuid: ^2.0.4

flutter:
  plugin:
    androidPackage: com.example.passkit
    pluginClass: PasskitPlugin
