name: pass_flutter
description: A Flutter library for getting and reading Apple Wallet passes.
version: 1.1.2
homepage: https://github.com/alexeynobody/pass-flutter

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: "2.0.13"
  dio: "3.0.9"
  path_provider: "1.6.5"
  uuid: "2.2.0"
  path: "1.6.4"
  equatable: "1.2.2"
  json_annotation: "3.0.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: "3.3.0"
  build_runner: "1.10.0"
  pedantic: "1.9.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.alexeynobody.pass_flutter
        pluginClass: PassFlutterPlugin
      ios:
        pluginClass: PassFlutterPlugin