name: pass_flutter
version: 1.2.1
description: A Flutter library for getting and reading Apple Wallet passes.
homepage: https://github.com/alexeynobody/pass-flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.alexeynobody.pass_flutter
        pluginClass: PassFlutterPlugin
      ios:
        pluginClass: PassFlutterPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^2.0.13
  dio: ^3.0.10
  path_provider: ^1.6.18
  uuid: ^2.2.2
  path: ^1.6.4
  equatable: ^1.2.5
  json_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0
  build_runner: ^1.10.3
  pedantic: ^1.9.2